apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      - system:masters
      rolearn: arn:aws:iam::013241101417:role/UdacityFlaskDeployCBKubectlRole/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1TEIVFQGWC2YV
      username: test
    - groups:
      - system:masters
      rolearn: arn:aws:iam::013241101417:role/UdacityFlaskDeployCBKubectlRole
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
