apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:masters
      rolearn: arn:aws:iam::013241101417:role/UdacityFlaskDeployCBKubectlRole
      username: build  
kind: ConfigMap
metadata:
  creationTimestamp: '2023-06-24T09:04:31Z'
  name: aws-auth
  namespace: kube-system
  resourceVersion: '1857'
  uid: c71e84c6-ebc1-4824-81da-c6c3b43a603c
